In [1]:
# train the deep learning model with training data
import glob
import os
import pickle
from PIL import Image
import numpy as np

In [2]:
print(np.__version__)

1.15.0


In [1]:
!pip install pandas==0.21.0

  Found existing installation: pandas 0.20.1
    Uninstalling pandas-0.20.1:
      Successfully uninstalled pandas-0.20.1


You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [3]:
import tensorflow as tf

C:\Users\rahsood\AppData\Local\Continuum\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
from feature_extractor import FeatureExtractor

Using TensorFlow backend.


In [5]:
fe = FeatureExtractor()
# This step downloads the .h5 file:
# Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels.h5
# 427769856/553467096 [======================>.......] - ETA: 2:26

In [6]:
for img_path in sorted(glob.glob('img/*.jpg')):
    print(img_path)
    img = Image.open(img_path)  # PIL image
    feature = fe.extract(img)
    feature_path = 'img/' + os.path.splitext(os.path.basename(img_path))[0] + '.pkl'
    pickle.dump(feature, open(feature_path, 'wb'))

img\2127.jpg
img\2131.jpg
img\2134.jpg
img\2135.jpg
img\2137.jpg
img\2138.jpg
img\2139.jpg
img\2140.jpg
img\2239.jpg
img\2241.jpg
img\2242.jpg


In [7]:
# TEST INDIVIDUAL BLOCK OF CODE
img = Image.open("img/2135.jpg")  # PIL image
# uploaded_img_path = "static/uploaded/" + datetime.now().isoformat() + "_" + file.filename
# img.save(uploaded_img_path)

query = fe.extract(img)
print(type(query))
print(np.shape(query))

<class 'numpy.ndarray'>
(4096,)


In [8]:
vec1 = fe.extract(Image.open("img/2135.jpg"))

In [9]:
vec1.shape

(4096,)

In [10]:
vec2 = fe.extract(Image.open("img/2137.jpg"))
vec2

array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
       0.04746252], dtype=float32)

In [11]:
vec2[0] = 1
vec2[1] = 2
vec2[2] = 3
vec2

array([1.        , 2.        , 3.        , ..., 0.        , 0.        ,
       0.04746252], dtype=float32)

In [15]:
vec_new = np.concatenate((vec1, vec2), axis=0)

In [16]:
vec_new.shape

(8192,)

In [17]:
print(vec_new[0:3],vec_new[4096:4099])

[0. 0. 0.] [1. 2. 3.]


In [12]:
import pandas as pd
df_cars = pd.read_csv("D:/Users/rahsood/Downloads/transformers-prebucketing-10k-fixed-10k-production-batch-results-2019-08-22T12-57-21.csv")

In [13]:
df_cars.columns

Index(['createdAt', 'id', 'inputRecord/createdAt',
       'inputRecord/data/BodyTypeCode', 'inputRecord/data/StockNumber',
       'inputRecord/data/url01', 'inputRecord/data/url02',
       'inputRecord/data/url03', 'inputRecord/data/url04',
       'inputRecord/data/url05', 'inputRecord/data/url06',
       'inputRecord/data/url07', 'inputRecord/data/url08',
       'inputRecord/data/url09', 'inputRecord/data/url10', 'inputRecord/id',
       'resultData/1_comments', 'resultData/1_damageLocation/0',
       'resultData/1_damageLocation/1', 'resultData/1_damageLocation/2',
       'resultData/1_damageLocation/3', 'resultData/1_damageLocation/4',
       'resultData/1_damageLocation/5', 'resultData/1_scale',
       'resultData/1_visibleDamage', 'resultData/2_comments',
       'resultData/2_damageLocation/0', 'resultData/2_damageLocation/1',
       'resultData/2_damageLocation/2', 'resultData/2_damageLocation/3',
       'resultData/2_damageLocation/4', 'resultData/2_damageLocation/5',
       're

In [14]:
df_cars.drop(columns=['inputRecord/id',
       'resultData/1_comments', 'resultData/1_damageLocation/0',
       'resultData/1_damageLocation/1', 'resultData/1_damageLocation/2',
       'resultData/1_damageLocation/3', 'resultData/1_damageLocation/4',
       'resultData/1_damageLocation/5', 'resultData/1_scale',
       'resultData/1_visibleDamage', 'resultData/2_comments',
       'resultData/2_damageLocation/0', 'resultData/2_damageLocation/1',
       'resultData/2_damageLocation/2', 'resultData/2_damageLocation/3',
       'resultData/2_damageLocation/4', 'resultData/2_damageLocation/5',
       'resultData/2_scale', 'resultData/BodyTypeCode',
       'resultData/StockNumber', 'resultData/qc_comments','resultData/2_visibleDamage', 'resultData/qc_visibleDamage', 'resultData/url01', 'resultData/url02',
       'resultData/url03', 'resultData/url04', 'resultData/url05',
       'resultData/url06', 'resultData/url07', 'resultData/url08',
       'resultData/url09', 'resultData/url10'], axis=1, inplace=True)

In [15]:
df_cars['inputRecord/data/StockNumber'].head()

0    25607745
1    25655579
2    25583256
3    25638489
4    25644525
Name: inputRecord/data/StockNumber, dtype: int64

In [16]:
df_cars.rename(columns={'inputRecord/data/BodyTypeCode':'BodyTypeCode', 
                    'inputRecord/data/StockNumber':'StockNumber', 
                    'resultData/qc_scale':'Grade'}, inplace=True)

In [17]:
df_cars.rename(columns={'inputRecord/data/url01':'url01', 'inputRecord/data/url02':'url02', \
                    'inputRecord/data/url03':'url03', 'inputRecord/data/url04':'url04', \
                    'inputRecord/data/url05':'url05', 'inputRecord/data/url06':'url06', \
                   'inputRecord/data/url07':'url07', 'inputRecord/data/url08':'url08', \
                    'inputRecord/data/url09':'url09', 'inputRecord/data/url10':'url10'}, inplace=True)

In [18]:
df_cars.rename(columns={'resultData/qc_damageLocation/0':'dmgLoc0', 'resultData/qc_damageLocation/1':'dmgLoc1',
                    'resultData/qc_damageLocation/2':'dmgLoc2', 'resultData/qc_damageLocation/3':'dmgLoc3',
                    'resultData/qc_damageLocation/4':'dmgLoc4', 'resultData/qc_damageLocation/5':'dmgLoc5'}, inplace=True)

In [19]:
df_cars.columns

Index(['createdAt', 'id', 'inputRecord/createdAt', 'BodyTypeCode',
       'StockNumber', 'url01', 'url02', 'url03', 'url04', 'url05', 'url06',
       'url07', 'url08', 'url09', 'url10', 'dmgLoc0', 'dmgLoc1', 'dmgLoc2',
       'dmgLoc3', 'dmgLoc4', 'dmgLoc5', 'Grade'],
      dtype='object')

In [20]:
df_cars.drop(columns=['url01', 'url02', 'url03', 'url04', 'url05', 'url06',
       'url07', 'url08', 'url09', 'url10'], axis=1, inplace=True)

In [21]:
df_cars.columns

Index(['createdAt', 'id', 'inputRecord/createdAt', 'BodyTypeCode',
       'StockNumber', 'dmgLoc0', 'dmgLoc1', 'dmgLoc2', 'dmgLoc3', 'dmgLoc4',
       'dmgLoc5', 'Grade'],
      dtype='object')

In [22]:
df_cars.head()

createdAt                                    id  \
0  2019-08-21T08:56:30.563Z  03916647-d49c-4485-9165-383e1d88659a   
1  2019-08-21T08:54:57.928Z  c384d9ae-9e4a-473c-84cb-791a7c27e45a   
2  2019-08-21T08:54:46.680Z  bea767e9-db9a-4f8e-94a3-d9a71bd74137   
3  2019-08-21T08:54:40.145Z  fc1f75b9-a349-47fd-a18f-0745d2373ef0   
4  2019-08-21T08:54:13.670Z  4eec7916-db32-485b-974d-89f831f3786d   

      inputRecord/createdAt BodyTypeCode  StockNumber dmgLoc0 dmgLoc1  \
0  2019-08-10T15:23:05.770Z           VN     25607745   Front  Driver   
1  2019-08-10T15:23:05.771Z           4H     25655579   Front  Driver   
2  2019-08-10T15:23:05.770Z           VN     25583256   Front    Rear   
3  2019-08-10T15:23:05.771Z           4C     25638489   Front  Driver   
4  2019-08-10T15:23:05.771Z           VN     25644525   Front  Driver   

     dmgLoc2 dmgLoc3   dmgLoc4 dmgLoc5  Grade  
0  Passenger    Rear  Interior    Roof      1  
1        NaN     NaN       NaN     NaN      4  
2        NaN     NaN       NaN     NaN      3  
3   Interior     NaN       NaN     NaN      2  
4  Passenger    Rear  Interior    Roof      1

In [23]:
a = pd.DataFrame()
b = pd.DataFrame()
# c = pd.concat(a,b) # errors out:
# TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

c = pd.concat([a,b]) # works.

In [24]:
df_cars_train = pd.DataFrame()
for grade in range(0,6):
    df = df_cars[df_cars['Grade']==grade].sample(n = 100, random_state = 2) 
    df_cars_train = pd.concat([df_cars_train, df])

In [25]:
df_cars_train['Grade'].value_counts()

5    100
4    100
3    100
2    100
1    100
0    100
Name: Grade, dtype: int64

In [26]:
df_cars_train[['StockNumber','Grade']].tail()

StockNumber  Grade
587      25684688      5
9640     23697818      5
9420     23927627      5
866      25492392      5
3804     25635164      5

In [27]:
df_cars_train[['StockNumber','Grade']].head()

StockNumber  Grade
5064     25014225      0
6238     24205665      0
7081     24027197      0
2829     24563390      0
3741     24431341      0

In [28]:
df_cars_train = df_cars_train.sample(frac=1).reset_index(drop=True)

In [29]:
df_cars_train[['StockNumber','Grade']].head()

StockNumber  Grade
0     24214918      4
1     24900394      4
2     24337626      5
3     24768596      3
4     24803130      1

In [30]:
df_cars_train['Grade'].value_counts()

5    100
4    100
3    100
2    100
1    100
0    100
Name: Grade, dtype: int64

In [31]:
len(df_cars_train)

600

In [120]:
vec0 = np.ndarray((0,))
vec01 = np.concatenate((vec0, vec1))

In [139]:
vecA = np.zeros((4096,))

In [121]:
np.shape(vec01)

(4096,)

## Saving as a Dictionary of Vectors

In [33]:
err_count = 3
print('Error Count' + str(err_count))

Error Count3


In [34]:
i = 0
err_count = 0
dict_stock_vectors = {}
for rec in df_cars_train[['StockNumber','Grade']].itertuples():
    stock = rec[1]
    folder = str(rec[1])
    print('..processing '+folder)
    grade = str(rec[2])
    print(grade)
    #     print(rec.url01)
    i = i+1
    stock_img_vector = np.ndarray((0,))  #blank vector
    for j in range(0,6):
        filename='url0'+str(j+1)+'.jpg'
        img_path = 'D:/IAA/data/images/dataset/'+grade+'/'+folder + '/' + filename
#         print(img_path)
        if os.path.exists(img_path):          
            indiv_img_vector = fe.extract(Image.open(img_path))
            stock_img_vector = np.concatenate((stock_img_vector, indiv_img_vector), axis=0)
        else:
            print('Error for ' + img_path)
            err_count = err_count + 1
            indiv_img_vector = np.zeros((4096,))
            stock_img_vector = np.concatenate((stock_img_vector, indiv_img_vector), axis=0)
#         try:
#             wget.download(urlname,out='IAA/cars/'+filename)
#         except:
#             print('Error')
#             continue
#     print(stock_img_vector.shape)
    dict_stock_vectors[stock] = stock_img_vector
#     if (i==5):
#         break
print('Error Count' + str(err_count))
print('End of Vector Creation')


..processing 24214918
4
..processing 24900394
4
..processing 24337626
5
..processing 24768596
3
..processing 24803130
1
..processing 23769812
5
..processing 24282878
2
..processing 23903697
5
..processing 24217807
4
..processing 23865649
1
..processing 24615155
2
..processing 24644204
0
..processing 25530173
1
..processing 25615200
5
..processing 24415917
2
..processing 25580006
5
..processing 24529485
0
..processing 24146452
4
Error for D:/IAA/data/images/dataset/4/24146452/url06.jpg
..processing 24448909
3
..processing 23664696
4
Error for D:/IAA/data/images/dataset/4/23664696/url01.jpg
..processing 25525493
5
Error for D:/IAA/data/images/dataset/5/25525493/url04.jpg
..processing 25080244
1
..processing 24605740
2
..processing 24291857
5
Error for D:/IAA/data/images/dataset/5/24291857/url03.jpg
..processing 25163335
0
..processing 24324896
0
..processing 24717055
4
..processing 24838651
5
..processing 25060780
5
..processing 23741357
5
..processing 24017360
1
..processing 24477310
0


..processing 25499183
5
..processing 23582599
2
..processing 23724222
1
..processing 25097726
2
..processing 24869762
1
..processing 25571105
2
..processing 24484244
5
..processing 25516954
3
..processing 24301206
4
..processing 25667497
0
..processing 24438134
0
..processing 24516381
4
..processing 24049361
3
..processing 25493171
4
..processing 24431341
0
..processing 25129469
5
..processing 25078595
0
..processing 24189853
4
..processing 24957491
1
Error for D:/IAA/data/images/dataset/1/24957491/url03.jpg
..processing 25179043
0
Error for D:/IAA/data/images/dataset/0/25179043/url04.jpg
..processing 25232462
5
..processing 24226893
1
..processing 24239310
2
..processing 23994172
0
..processing 25264190
5
Error for D:/IAA/data/images/dataset/5/25264190/url02.jpg
..processing 25277877
0
..processing 24123846
2
..processing 23928075
2
..processing 23937316
1
..processing 24269755
3
..processing 24462487
1
Error for D:/IAA/data/images/dataset/1/24462487/url04.jpg
..processing 24509546
5


..processing 23994954
4
..processing 23807284
5
Error for D:/IAA/data/images/dataset/5/23807284/url06.jpg
..processing 24482296
1
..processing 23931232
2
..processing 24091245
4
..processing 23537387
5
..processing 23584199
5
..processing 25555220
5
..processing 24517843
1
..processing 25061293
4
Error for D:/IAA/data/images/dataset/4/25061293/url04.jpg
..processing 24270940
5
..processing 24382670
3
..processing 24621016
3
..processing 24006681
4
..processing 24175927
2
Error for D:/IAA/data/images/dataset/2/24175927/url03.jpg
..processing 24315025
3
..processing 23871227
0
..processing 24477908
3
..processing 23977715
3
..processing 24207500
4
..processing 25566104
2
..processing 24480205
4
..processing 25052412
0
..processing 24710274
1
..processing 23815265
3
..processing 24239258
5
..processing 23875180
3
..processing 24133290
3
Error for D:/IAA/data/images/dataset/3/24133290/url01.jpg
..processing 24675426
1
..processing 25454402
3
..processing 24407327
3
Error for D:/IAA/data/im

In [35]:
len(dict_stock_vectors)

600

## Saving as a List of Vectors

In [ ]:
i = 0
list_stock_vectors = []
for rec in df_cars_train[['StockNumber','Grade']].itertuples():
    stock = rec[1]
    folder = str(rec[1])
    print('..processing '+folder)
    grade = str(rec[2])
    print(grade)
    #     print(rec.url01)
    i = i+1
    stock_img_vector = np.ndarray((0,))  #blank vector
    for j in range(0,6):
        filename='url0'+str(j+1)+'.jpg'
        img_path = 'D:/IAA/data/images/dataset/'+grade+'/'+folder + '/' + filename
#         print(img_path)
        if os.path.exists(img_path):          
            indiv_img_vector = fe.extract(Image.open(img_path))
            stock_img_vector = np.concatenate((stock_img_vector, indiv_img_vector), axis=0)
        else:
            print('Error for ' + img_path)
            indiv_img_vector = np.zeros((4096,))
            stock_img_vector = np.concatenate((stock_img_vector, indiv_img_vector), axis=0)
#         try:
#             wget.download(urlname,out='IAA/cars/'+filename)
#         except:
#             print('Error')
#             continue
#     print(stock_img_vector.shape)
    list_stock_vectors[stock] = stock_img_vector
    if (i==100):
        break
    

In [135]:
if os.path.exists('D:/IAA/data/images/dataset/0/25368493/url04.jpg'):
    print('success')
else:
    print('failure')

failure


In [129]:
dict_stock_vectors[25209736]

array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
       0.04383248])

## Pickle Steps
* Saving the Pickle File / Database/Dictionary of Vectors file

In [36]:
database_filename = 'stock_vectors.file'

with open(database_filename,'wb') as wfp:
    pickle.dump(dict_stock_vectors, wfp)
fn_status = 'success'
print(fn_status)


success


* Opening the Pickle File / Database/Dictionary of Vectors file

In [37]:
database_filename = 'stock_vectors.file'

if os.path.exists(database_filename):
    with open(database_filename,'rb') as rfp: 
        database = pickle.load(rfp)
        print(database.keys())

dict_keys([24214918, 24900394, 24337626, 24768596, 24803130, 23769812, 24282878, 23903697, 24217807, 23865649, 24615155, 24644204, 25530173, 25615200, 24415917, 25580006, 24529485, 24146452, 24448909, 23664696, 25525493, 25080244, 24605740, 24291857, 25163335, 24324896, 24717055, 24838651, 25060780, 23741357, 24017360, 24477310, 25592331, 24212463, 24206606, 24074222, 24066510, 24085627, 24526310, 23891252, 25372350, 24072243, 24380913, 23996486, 24172981, 25589031, 24412359, 24265273, 24463342, 23793579, 24769257, 25311486, 23674850, 24569943, 24650169, 24013992, 24687482, 24637920, 25228108, 24007042, 23704706, 24335826, 23962143, 24050860, 24168548, 23703576, 25664901, 24233730, 23668346, 24640319, 24476816, 24171578, 25496451, 25521007, 24956340, 24024569, 23606095, 24642403, 24688166, 24576248, 24319324, 24758821, 24542018, 24094312, 24372948, 24064727, 24524210, 25157840, 25619789, 23831451, 23580867, 23596236, 24156531, 25706731, 24769883, 25130127, 24228659, 23848385, 25582303,

In [38]:
len(database)

600

In [39]:
train_matrix = np.ndarray((600, 4096*6))

In [40]:
train_matrix.shape

(600, 24576)

In [41]:
train_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
print(len(database.keys()))

600


In [87]:
df_cars_train[['StockNumber','Grade']].head()

StockNumber  Grade
0     24214918      4
1     24900394      4
2     24337626      5
3     24768596      3
4     24803130      1

In [92]:
len(df_cars_train)

600

In [102]:
database.keys()

dict_keys([24214918, 24900394, 24337626, 24768596, 24803130, 23769812, 24282878, 23903697, 24217807, 23865649, 24615155, 24644204, 25530173, 25615200, 24415917, 25580006, 24529485, 24146452, 24448909, 23664696, 25525493, 25080244, 24605740, 24291857, 25163335, 24324896, 24717055, 24838651, 25060780, 23741357, 24017360, 24477310, 25592331, 24212463, 24206606, 24074222, 24066510, 24085627, 24526310, 23891252, 25372350, 24072243, 24380913, 23996486, 24172981, 25589031, 24412359, 24265273, 24463342, 23793579, 24769257, 25311486, 23674850, 24569943, 24650169, 24013992, 24687482, 24637920, 25228108, 24007042, 23704706, 24335826, 23962143, 24050860, 24168548, 23703576, 25664901, 24233730, 23668346, 24640319, 24476816, 24171578, 25496451, 25521007, 24956340, 24024569, 23606095, 24642403, 24688166, 24576248, 24319324, 24758821, 24542018, 24094312, 24372948, 24064727, 24524210, 25157840, 25619789, 23831451, 23580867, 23596236, 24156531, 25706731, 24769883, 25130127, 24228659, 23848385, 25582303,

In [105]:
stock_list = []
X_matrix = np.ndarray((600, 4096*6))
y_list = np.ndarray((600,))
for i, stock in enumerate(database.keys()): #df_cars_train['StockNumber']:
#     print(i)
#     print(stock)
#     print(database[stock])
    X_matrix[i] = database[stock]
    y_list[i] = df_cars_train[df_cars_train['StockNumber']==stock]['Grade']
    stock_list.append(stock)

In [110]:
type(y_list), type(stock_list)

(numpy.ndarray, list)

In [107]:
y_list[0:10]

array([4., 4., 5., 3., 1., 5., 2., 5., 4., 1.])

In [108]:
stock_list[0:10]

[24214918,
 24900394,
 24337626,
 24768596,
 24803130,
 23769812,
 24282878,
 23903697,
 24217807,
 23865649]

In [50]:
train_matrix

array([[0.        , 0.        , 0.        , ..., 0.        , 0.03124353,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00509369],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [79]:
cars_svd = TruncatedSVD(n_components=700, n_iter=20, random_state=42)

In [80]:
cars_svd.fit(train_matrix)  

TruncatedSVD(algorithm='randomized', n_components=700, n_iter=20,
       random_state=42, tol=0.0)

In [81]:
train_matrix.shape

(600, 24576)

In [82]:
train_matrix_small = cars_svd.transform(train_matrix)  

In [83]:
train_matrix_small.shape

(600, 600)

In [84]:
train_matrix_small

array([[ 1.49694514e+00,  2.05191126e-01,  6.23589542e-01, ...,
        -2.18002870e-02,  1.53786343e-02,  1.00177111e-02],
       [ 1.56449366e+00,  1.12651895e-01,  5.98196801e-01, ...,
         1.10385443e-02,  3.58071078e-02, -1.16122548e-02],
       [ 1.58269420e+00, -2.60100274e-01, -3.81666308e-01, ...,
        -1.52446571e-02,  5.39891373e-03,  2.73660800e-02],
       ...,
       [ 1.45271402e+00, -3.76696023e-01,  1.08187875e-01, ...,
        -1.86393066e-02, -5.60848664e-02, -3.24386706e-02],
       [ 1.55665768e+00,  5.22872823e-01,  1.45421777e-01, ...,
         6.80399435e-03,  1.53164493e-03,  6.93523609e-03],
       [ 1.69842744e+00, -3.06376077e-02,  5.20598398e-01, ...,
         2.18037041e-02, -7.22129054e-02,  1.84793365e-02]])

In [86]:
print(cars_svd.explained_variance_ratio_.sum())  

1.0


In [117]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_matrix, y_list, test_size=0.20, random_state=42)

In [118]:
len(y_train), len(y_test), len(y_list)

(480, 120, 600)

In [119]:
len(X_train), len(X_test), len(X_matrix)

(480, 120, 600)

In [120]:
from sklearn.linear_model import LogisticRegression

# logreg = LogisticRegression(multi_class='multinomial', solver = 'lbfgs')
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

C:\Users\rahsood\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\rahsood\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [121]:
logreg.score(X_test, y_test)

0.475

In [122]:
logreg.score(X_train, y_train)

1.0

In [124]:
y_pred = logreg.predict(X_test)

In [125]:
y_pred

array([0., 3., 3., 4., 2., 2., 0., 3., 0., 0., 1., 3., 0., 4., 1., 4., 1.,
       0., 1., 5., 5., 4., 2., 2., 5., 4., 2., 4., 1., 0., 4., 0., 2., 0.,
       3., 5., 1., 1., 5., 5., 1., 5., 2., 1., 0., 3., 5., 5., 5., 1., 1.,
       4., 0., 4., 4., 4., 5., 4., 4., 2., 2., 0., 3., 5., 3., 0., 2., 0.,
       2., 2., 3., 5., 5., 1., 2., 4., 5., 4., 3., 2., 2., 1., 1., 4., 3.,
       0., 1., 5., 1., 4., 0., 5., 5., 1., 5., 1., 4., 0., 0., 1., 2., 5.,
       0., 2., 5., 0., 4., 0., 5., 4., 4., 5., 1., 3., 1., 5., 4., 5., 0.,
       0.])

In [126]:
y_test

array([0., 2., 4., 3., 2., 2., 2., 3., 1., 0., 5., 5., 0., 4., 1., 3., 1.,
       0., 0., 5., 5., 2., 1., 2., 3., 3., 2., 4., 2., 0., 4., 1., 2., 0.,
       4., 5., 1., 1., 4., 4., 1., 5., 3., 1., 0., 3., 5., 3., 5., 2., 1.,
       3., 0., 5., 5., 3., 3., 4., 5., 3., 3., 1., 2., 3., 2., 2., 2., 0.,
       4., 2., 2., 2., 4., 1., 3., 3., 4., 3., 4., 2., 5., 1., 1., 0., 3.,
       0., 1., 5., 2., 5., 1., 2., 4., 0., 3., 1., 3., 0., 0., 1., 2., 4.,
       0., 2., 5., 2., 3., 0., 5., 4., 4., 5., 2., 4., 1., 4., 2., 1., 1.,
       1.])

In [130]:
abs(y_pred - y_test)

array([0., 1., 1., 1., 0., 0., 2., 0., 1., 0., 4., 2., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 2., 1., 0., 2., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 2., 0., 1., 0.,
       1., 0., 1., 1., 1., 2., 0., 1., 1., 1., 1., 1., 2., 1., 2., 0., 0.,
       2., 0., 1., 3., 1., 0., 1., 1., 1., 1., 1., 0., 3., 0., 0., 4., 0.,
       0., 0., 0., 1., 1., 1., 3., 1., 1., 2., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 2., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 2., 4., 1.,
       1.])

In [131]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.61      0.82      0.70        17
         1.0       0.67      0.64      0.65        22
         2.0       0.59      0.40      0.48        25
         3.0       0.25      0.14      0.18        21
         4.0       0.27      0.33      0.30        18
         5.0       0.40      0.59      0.48        17

   micro avg       0.47      0.47      0.48       120
   macro avg       0.46      0.49      0.46       120
weighted avg       0.47      0.47      0.46       120



In [140]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=200)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_rf_pred=clf.predict(X_test)

In [141]:
clf.score(X_test, y_test)

0.4

In [142]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_rf_pred)

0.4

In [135]:
from sklearn.neighbors import KNeighborsClassifier

# 2. instantiate the model (with the default parameters)
knn = KNeighborsClassifier()

# 3. fit the model with data (occurs in-place)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [136]:
knn.score(X_test, y_test)

0.3

In [137]:
from sklearn.naive_bayes import MultinomialNB

# 2. instantiate a Multinomial Naive Bayes model
nb = MultinomialNB()

In [138]:
nb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [139]:
nb.score(X_test, y_test)

0.35

In [52]:
from sklearn.decomposition import TruncatedSVD
from sklearn.random_projection import sparse_random_matrix

In [53]:
# X = sparse_random_matrix(100, 100, density=0.01, random_state=42)
# svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
# svd.fit(X)  

TruncatedSVD(algorithm='randomized', n_components=5, n_iter=7,
       random_state=42, tol=0.0)

In [54]:
# print(svd.explained_variance_ratio_)  

[0.06063696 0.05842599 0.04970872 0.04344233 0.03723615]


In [55]:
# print(svd.explained_variance_ratio_.sum())  

0.2494501382848952


In [56]:
print(svd.singular_values_)  

[2.58418571 2.52453902 2.32011672 2.17531753 2.04439905]


In [43]:
dists = np.linalg.norm(features - query, axis=1)  # Do search
type(dists), np.shape(dists)

(numpy.ndarray, (9,), ())

In [45]:
dists

array([0.72304   , 0.8065041 , 0.60158205, 0.        , 0.70538986,
       0.5522854 , 0.9774229 , 0.96457505, 0.8962573 ], dtype=float32)

In [46]:
ids = np.argsort(dists)[:5] # Top 30 results
ids

array([3, 5, 2, 4, 0], dtype=int64)

In [47]:
scores = [(dists[id], img_paths[id]) for id in ids]	
scores

IndexError: list index out of range

In [18]:
import os
import numpy as np
from PIL import Image
from feature_extractor import FeatureExtractor
import glob
import pickle
from datetime import datetime
# from flask import Flask, request, render_template

# app = Flask(__name__)

In [37]:
# Read image features
fe = FeatureExtractor()
features = []
img_paths = []

i = 0
for feature_path in glob.glob("img\*.pkl"):    
    print(feature_path)
    i= i+1
    if i<10:
        features.append(pickle.load(open(feature_path, 'rb')))
    
#     img_paths.append('static/img/' + os.path.splitext(os.path.basename(feature_path))[0] + '.jpg')

img\2127.pkl
img\2131.pkl
img\2134.pkl
img\2135.pkl
img\2137.pkl
img\2138.pkl
img\2139.pkl
img\2140.pkl
img\2239.pkl
img\2241.pkl
img\2242.pkl


In [39]:
len(features), features[0]

(9, array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.05603974], dtype=float32))

In [27]:
feature_path = glob.glob("D:\img\*")

feature_path[0], os.path.splitext(os.path.basename(feature_path[0]))[0] + '.jpg'

('D:\\img\\1558.jpg', '1558.jpg')

In [ ]:


@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        file = request.files['query_img']

        img = Image.open(file.stream)  # PIL image
        uploaded_img_path = "static/uploaded/" + datetime.now().isoformat() + "_" + file.filename
        img.save(uploaded_img_path)

        query = fe.extract(img)
        dists = np.linalg.norm(features - query, axis=1)  # Do search
        ids = np.argsort(dists)[:5] # Top 30 results
        scores = [(dists[id], img_paths[id]) for id in ids]	

        return render_template('index.html',
                               query_path=uploaded_img_path,
                               scores=scores)
    else:
        return render_template('index.html')

if __name__=="__main__":
    app.run("0.0.0.0")